# Generated by Django 5.0.3 on 2024-04-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TweetRecognitionApp', '0002_topic_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic',
        ),
    ]
