# Generated by Django 5.0.3 on 2024-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetRecognitionApp', '0005_topic_negativewords_topic_neutralwords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='actual_data',
            field=models.JSONField(default=[1, 2, 0, 2, 1, 1, 1, 0]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='predicted_data',
            field=models.JSONField(default=[1, 2, 0, 2, 2, 2, 2, 1]),
            preserve_default=False,
        ),
    ]
