# Generated by Django 5.0.3 on 2024-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetRecognitionApp', '0008_rename_solo_bert_percentages_topic_solo_bert_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='svm_bert_actual_data',
            field=models.JSONField(default=[1, 2, 0, 1, 2, 1, 2, 0]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='svm_bert_percent',
            field=models.JSONField(default=[50, 30, 20]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='svm_bert_predicted_data',
            field=models.JSONField(default=[1, 2, 0, 1, 2, 1, 2, 0]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='svm_bow_actual_data',
            field=models.JSONField(default=[1, 2, 0, 1, 2, 1, 2, 0]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='svm_bow_percentage',
            field=models.JSONField(default=[60, 30, 10]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='svm_bow_predicted_data',
            field=models.JSONField(default=[1, 2, 0, 1, 2, 1, 2, 0]),
            preserve_default=False,
        ),
    ]
